"""empty message

Revision ID: 65144ac762c8
Revises: 
Create Date: 2020-03-07 21:40:24.513141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65144ac762c8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tweets',
    sa.Column('tweet_id', sa.BigInteger(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('inpression', sa.Integer(), nullable=True),
    sa.Column('engagement', sa.Integer(), nullable=True),
    sa.Column('retweet', sa.Integer(), nullable=True),
    sa.Column('reply', sa.Integer(), nullable=True),
    sa.Column('like', sa.Integer(), nullable=True),
    sa.Column('profile_click', sa.Integer(), nullable=True),
    sa.Column('url_click', sa.Integer(), nullable=True),
    sa.Column('hashtag_click', sa.Integer(), nullable=True),
    sa.Column('detail_click', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('tweet_id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=15, collation='utf8mb4_general_ci'), nullable=False),
    sa.Column('display_name', sa.String(length=50, collation='utf8mb4_general_ci'), nullable=False),
    sa.Column('email', sa.String(length=256, collation='utf8mb4_general_ci'), nullable=False),
    sa.Column('password', sa.String(length=1024, collation='utf8mb4_general_ci'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('tweets')
    # ### end Alembic commands ###
