"""empty message

Revision ID: 12c12f0af10b
Revises: 
Create Date: 2020-03-05 20:00:28.167647

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '12c12f0af10b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=15, collation='utf8mb4_general_ci'), nullable=False),
    sa.Column('display_name', sa.String(length=50, collation='utf8mb4_general_ci'), nullable=False),
    sa.Column('email', sa.String(length=256, collation='utf8mb4_general_ci'), nullable=False),
    sa.Column('password', sa.String(length=1024, collation='utf8mb4_general_ci'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('name')
    )
    op.drop_table('tweets')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tweets',
    sa.Column('tweet_id', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False),
    sa.Column('content', mysql.TEXT(collation='utf8mb4_general_ci'), nullable=True),
    sa.Column('date', mysql.DATETIME(), nullable=True),
    sa.Column('inpression', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('engagement', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('retweet', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('reply', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('like', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('profile_click', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('url_click', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('hashtag_click', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('detail_click', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('tweet_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('users')
    # ### end Alembic commands ###
